config/routes.rb
Rails.application.routes.draw do
	
  	authenticate :user do
	  #invoke add student to classes
	  get  "course_classes/registrations" => "course_classes#registrations"	
	  get  "course_classes/add_student" => "course_classes#add_student"	
	  get  "course_classes/remove_registration" => "course_classes#remove_registration"  
	  get  "course_classes/registration" => "course_classes#registration"  
	  get  "course_classes/employees" => "course_classes#employees"	
	  get  "course_classes/add_employee" => "course_classes#add_employee"	
	  get  "course_classes/remove_employee" => "course_classes#remove_employee"  
	  get  "course_classes/documents" => "course_classes#documents"	
	  post "course_classes/add_document" => "course_classes#add_document"
	  get  "course_classes/remove_document" => "course_classes#remove_document"  
	  get  "course_classes/clear_search" => "course_classes#clear_search"  
	  get  "course_classes/generate_list_of_presence" => "course_classes#generate_list_of_presence"  
	  get  "course_classes/close_course_class" => "course_classes#close_course_class"  
	  get  "course_classes/reopen_course_class" => "course_classes#reopen_course_class"  
	  get  "documents/download_file" => "documents#download_file"
	  get  "students/add_for_select" => "students#add_for_select"
	  get  "students/clear_search" => "students#clear_search"
	  get  "employees/add_for_select" => "employees#add_for_select"
	  get  "employees/clear_search" => "employees#clear_search"
      get  "cities/clear_search" => "cities#clear_search"
      get  "institutions/clear_search" => "institutions#clear_search"
      get  "courses/clear_search" => "courses#clear_search"
 	  get  "employee_categories/clear_search" => "employee_categories#clear_search"     
 	  get  "registration_statuses/clear_search" => "registration_statuses#clear_search"   
 	  get  "document_categories/clear_search" => "document_categories#clear_search"  
 	  get  "parameters/clear_search" => "parameters#clear_search"  
 	  post "accounts/update_user_account" => "accounts#update_user_account"  
 	  get  "accounts/activate_user" => "accounts#activate_user"  
 	  get  "accounts/inactivate_user" => "accounts#inactivate_user"  
 	  get  "accounts/roles" => "accounts#roles"	
	  get  "accounts/add_role" => "accounts#add_role"	
	  get  "accounts/remove_role" => "accounts#remove_role"    
	  get  "accounts/clear_search" => "accounts#clear_search"
	  get  "use_cases/clear_search" => "use_cases#clear_search"  
 	  get  "roles/clear_search" => "roles#clear_search"
 	  get  "roles/authorizations" => "roles#authorizations"	
 	  get  "roles/update_authorization" => "roles#update_authorization"
 	  get  "roles/add_for_select" => "roles#add_for_select"
 	  get  "registrations/clear_search" => "registrations#clear_search"
 	  get  "events/clear_search" => "events#clear_search"
 	  get  "events/previous_month" => "events#previous_month"
 	  get  "events/next_month" => "events#next_month"
 	  get  "events/add_participant" => "events#add_participant"
 	  get  "events/remove_participant" => "events#remove_participant"
 	  get  "events/participants" => "events#participants"

	  resources :events do
	  	get :autocomplete_employee_name, :on => :collection
	  end
	  resources :event_participants
	  resources :accounts
	  resources :roles
	  resources :authorizations
	  resources :use_cases
	  resources :documents
	  resources :employee_categories
	  resources :document_categories
	  resources :parameters	  
	  resources :registration_statuses
	  resources :institutions
	  resources :courses
	  resources :cities

	  resources :registrations do
	  	get :autocomplete_course_class_name, :on => :collection
	  end
	  
  	  resources :employees do
  	  	get :autocomplete_city_name, :on => :collection
  	  end

	  resources :students do
	  	get :autocomplete_city_name, :on => :collection
	  end

	  resources :course_classes do
	  	get :autocomplete_student_name, :on => :collection
	  	get :autocomplete_employee_name, :on => :collection
	  end

	end

	devise_for :users 
	devise_scope :user do
	  authenticated :user do
	    root 'visitors#index', as: :authenticated_root
	  end

	  unauthenticated do
	    root 'devise/sessions#new', as: :unauthenticated_root
	  end
	end

	root :to => "visitors#index"
end

app/controllers/course_classes_controller.rb
class CourseClassesController < ApplicationController
  
  before_action :set_course_class, only: [:show, :edit, :update, :destroy]
  respond_to :html, :js, :json, :pdf

  autocomplete :student, :name, :full => true, :extra_data => [:id]
  autocomplete :employee, :name, :full => true, :extra_data => [:id]

  include ModelSearchHelper
  include ListOfPresencePdfHelper

  def index
    @course_classes = self.search(params, CourseClass)
    respond_with(@course_classes)
  end

  def show
    respond_with(@course_class)
  end

  def new
    @course_class = CourseClass.new
    respond_with(@course_class)
  end

  def create
    @course_class = CourseClass.new(course_class_params)
    if @course_class.save
      redirect_to action: "index"
    else
      respond_with(@course_class)  
    end
  end

  def update
    if @course_class.update(course_class_params)
      redirect_to action: "index"
    else
      respond_with(@course_class)  
    end
  end

  def destroy
    @course_class.destroy
  end

  def clear_search
    session.delete :search_course_class_institution_name
    session.delete :search_course_class_course_name
    session.delete :search_course_class_name
    redirect_to action: "index"
  end

=begin
  MÉTODOS PARA ADICIONAR, REMOVER E EDITAR UMA MATRÍCULA DA TURMA
=end
  def registrations
    @course_class = CourseClass.find(params[:id])
    render '_form_add_students'
  end

  def registration
    @registration = Registration.find(params[:registration_id])

    session["url_back_registration"] = request.referrer
    
    redirect_to edit_registration_path(@registration)
  end

  def add_student
    
    @registration = Registration.new

    @course_class = CourseClass.find(params[:id])
    #limpa os erros que podem existir da requisição anterior
    @course_class.errors.clear
    
    begin
      @student = Student.find(params[:student_id])
      @course_class.registrations.each do |registration|
        if registration.student.id == @student.id
          @course_class.errors.add(:info, "O aluno já está matriculado.")
          render '_form_add_students'
          return
        end
      end
    rescue
      @course_class.errors.add(:info, "Aluno não encontrado. Por favor selecione um aluno válido.")
      render '_form_add_students'
      return
    end
    
    id_status_inicial = Parameter.where(name: Parameter::ID_STATUS_INICIAL_MATRICULA).first
    if id_status_inicial.nil? || id_status_inicial.value.nil?
      @course_class.errors.add(:info, "Parâmetro ID_STATUS_INICIAL_MATRICULA não está definido.")
      render '_form_add_students'
      return      
    else
      #rescue exception
      begin
        @registration_status = RegistrationStatus.find(id_status_inicial.value.to_i)
      rescue
        @course_class.errors.add(:info, "Status não encontrado com ID: " + id_status_inicial.value + ".")
        render '_form_add_students'
        return
      end

    end

    @registration.registration_status = @registration_status
    @registration.student = @student
    @course_class.registrations = Array.new if nil
    @course_class.registrations << @registration
    redirect_to :back
    
  end

  def remove_registration
    @course_class = CourseClass.find(params[:id])
    @course_class.registrations.delete(params[:registration_id])
    @course_class.save
    render "destroy_registration"
  end

=begin
  METODOS PARA ADICIONAR E REMOVER UM TUTOR DA TURMA
=end
  def employees
    @course_class = CourseClass.find(params[:id])
    render '_form_add_employees'
  end

  def add_employee

    @course_class = CourseClass.find(params[:id])
    #limpa os erros que podem existir da requisição anterior
    @course_class.errors.clear

    begin
      @employee = Employee.find(params[:employee_id])
      @course_class.employees.each do |employee|
        if employee.id == @employee.id
          @course_class.errors.add(:info, "O tutor já está cadastrado na turma.")
        end
      end
    rescue
      @course_class.errors.add(:info, "Tutor não encontrado. Por favor selecione um tutor válido. ")
    end
    
    #if occurred any erros, back to page
    if @course_class.errors.any?
      render '_form_add_employees'
      return
    end

    @course_class.employees << @employee
    @course_class.save

    redirect_to :back
    
  end

  def remove_employee
    @course_class = CourseClass.find(params[:id])
    @course_class.employees.delete(params[:employee_id])
    @course_class.save
    render "destroy_employee"
  end

=begin
  METODOS PARA ADICIONAR E REMOVER UM DOCUMENTO NA TURMA
=end
  def documents
    @course_class = CourseClass.find(params[:id])
    @course_class.document = Document.new
    render '_form_add_documents'
  end

  def add_document

    @course_class = CourseClass.find(params[:course_class_id])
    
    @course_class.document = Document.new(document_params)
    @course_class.document.file = params[:document][:file]
    @course_class.document.valid?

    #if occurred any erros, back to page
    if @course_class.document.errors.any?
      render '_form_add_documents'
      return
    end

    @course_class.document.save
    @course_class.documents << @course_class.document
    @course_class.save

    render '_form_add_documents'
    
  end

  def remove_document
    @course_class = CourseClass.find(params[:id])
    @course_class.document = Document.find(params[:document_id])

    @course_class.documents.delete(params[:document_id])
    @course_class.save
    @course_class.document.destroy

    FileUtils.remove_file(@course_class.document.path, force = true)
    render 'destroy_document'
  end  

  def close_course_class
    @course_class = CourseClass.find(params[:id])
    @course_class.update(:closed => true)
    redirect_to action: "index"
  end 

  def reopen_course_class
    @course_class = CourseClass.find(params[:id])
    @course_class.update(:closed => false)
    redirect_to action: "index"
  end   

  private
    def set_course_class
      @course_class = CourseClass.find(params[:id]) if params[:id].to_i > 0
    end

    def course_class_params
      params.require(:course_class).permit(:name, :institution_id, :course_id, :begin, :end, :closed)
    end

    def document_params
      params.require(:document).permit(:name, :document_category_id, :path, :extension, :size)
    end

end

app/helpers/course_classes_helper.rb
module CourseClassesHelper
end

app/views/course_classes/_form.html.erb
<script type="text/javascript">

$(document).ready(function() { 
  $(".date").mask("99/99/9999");
});

</script>
<%= simple_form_for @course_class, :html => { :class => "form-horizontal course_class" } do |f| %>

    <% if @course_class.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-body">
        <ul>
        <% @course_class.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, :class => 'col-sm-2 control-label' %>
    <div class="controls">
      <%= f.text_field :name, :autofocus => true, :class => 'form-control', :style=> 'max-width: 600px' %>
    </div>
    <%= error_span(@course_class[:name]) %>
  </div>

  <div class="form-group">
    <%= f.label :curso, :class => 'col-sm-2 control-label' %>
    <div class="controls" style="max-width:600px; display: -webkit-box;">
      <%= f.select(:course_id, Course.all.map{ |c| [c.name, c.id]}, {:value => :course_id}, {:class =>'form-control'})%>
    </div>
    <%= error_span(@course_class[:course]) %>
  </div>

  <div class="form-group">
    <%= f.label "Instituição", :class => 'col-sm-2 control-label' %>
    <div class="controls" style="max-width:600px; display: -webkit-box;">
      <%= f.select(:institution_id, Institution.all.map{ |c| [c.name, c.id]}, {:value => :institution_id}, {:class =>'form-control'})%>
    </div>
    <%= error_span(@course_class[:institution]) %>
  </div>

  <div class="form-group">
    <%= f.label "Início", :class => 'col-sm-2 control-label' %>
    <div class="controls">
      <%= f.text_field :begin, :class => 'form-control date', :style=> 'max-width: 200px'  %>
    </div>
    <%= error_span(@course_class[:begin]) %>
  </div>

  <div class="form-group">
    <%= f.label "Término", :class => 'col-sm-2 control-label' %>
    <div class="controls">
      <%= f.text_field :end, :class => 'form-control date', :style=> 'max-width: 200px'  %>
    </div>
    <%= error_span(@course_class[:end]) %>
  </div>

  <br><br>

  <%= error_span(@course_class[:begin]) %>

  <%= f.submit "Salvar Turma", :class => 'col-sm-offset-2 btn btn-primary' %>
  <%= link_to "Cancelar", course_classes_path, :class => 'btn btn-default' %>

 
<% end %>

app/views/course_classes/_form_add_documents.html.erb
<script type="text/javascript">
  $(document).ready(function() { 
     $('#document_file').on("change", function(){ 
      var name = this.value.split("/");;
      $('#file_name').val(name[name.length-1]);
    });
  });
</script>

<%= simple_form_for @course_class.document, 
    :html => { :class => "form-horizontal course_class", :multipart => true },
    :url => url_for(course_classes_add_document_path),
    :method => 'post' do |f| %>

  <div class="page-header">
    <h3>Documentos da Turma</h3>
  </div>

  <% if @course_class.document.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-body">
        <ul>
        <% @course_class.document.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

   <fieldset class="well the-fieldset">
      <div class="form-group">
       
        <div class="form-group">
          <%= f.label :nome, :class => 'col-sm-2 control-label' %>
          <div class="controls">
            <%= f.text_field :name, :autofocus => true, :class => 'form-control', :style=> 'max-width: 600px' %>
          </div>
          <%= error_span(@course_class.document[:name]) %>
        </div>

        <div class="form-group">
          <%= f.label :categoria, :class => 'col-sm-2 control-label' %>
          <div class="controls" style="max-width:600px; display: -webkit-box;">
            <%= f.select(:document_category_id, 
              DocumentCategory.all.map{ |c| [c.name, c.id]}, 
              {:value => :document_category_id}, 
              {:class =>'form-control'})%>
          </div>
          <%= error_span(@course_class.document[:document_category]) %>
        </div>

        <div class="form-inline" style="margin-left: -11px;">
          <%= f.label :arquivo, :class => 'col-sm-2 control-label' %>
          <input id="file_name" class="form-control" disabled="disabled" />
          <div class="fileUpload btn btn-default">
            <span>Escolha um arquivo</span>
            <%= f.file_field :file, :class => "upload"%>
          </div>
          <%= error_span(@course_class.document[:file]) %>
        </div>

        <br>

        <%= hidden_field_tag :course_class_id, @course_class.id %>
        <%= f.submit "Salvar Documento", 
            :disabled => !current_user.auth_to_add('document') || @course_class.closed,
            :class => 'col-sm-offset-2 btn btn-primary' %>

      </div>
    </fieldset>

  <!-- DOCUMENTS -->
  <div role="tabpanel" class="tab-pane active" id="students">
      <%- model_class = Document -%>
      <table class="table table-striped">
        <thead>
          <tr>
            <th><%= model_class.human_attribute_name(:nome) %></th>
            <th><%= model_class.human_attribute_name(:categoria) %></th>
            <th><%= model_class.human_attribute_name(:nome_original) %></th>
            <th><%= model_class.human_attribute_name("Extensão") %></th>
            <th><%=t '.actions', :default => "Ações" %></th>
          </tr>
        </thead>
        <tbody>
          <% @course_class.documents.each do |document| %>
            <tr id="document_<%=document.id%>">
              <td width="30%"><%= document.name %></td>
              <td><%= (document.document_category.nil? ? "" : document.document_category.name) %></td>
              <td><%= document.original_file_name %></td>
              <td><%= document.extension %></td>
              <td>

                <%= link_to "Download", 
                    documents_download_file_path(:id => document.id),
                    :disabled => !current_user.auth_to_view('document'), 
                    :class => 'btn btn-success btn-xs' %>

                <%= link_to "Remove", 
                      course_classes_remove_document_path(:id => @course_class.id, :document_id => document.id),
                      :data => { :confirm => t('.confirm', :default => 'Tem certeza que deseja excluir o arquivo?') },
                      :remote => true,
                      :disabled => !current_user.auth_to_remove('document') || @course_class.closed,
                      :class=>'btn btn-xs btn btn-danger' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

  </div>

  <%= link_to "Voltar", course_classes_path, :class => 'btn btn-default' %>                      

<% end %>

app/views/course_classes/_form_add_employees.html.erb
<%= simple_form_for @course_class, 
    :html => { :class => "form-horizontal course_class"},
    :url => url_for(course_classes_add_employee_path),
    :method => 'get' do |f| %>


  <div class="page-header">
    <h3>Tutores</h3>
  </div>

  <!--GROUP FIND EMPLOYEE -->
  <fieldset class="well the-fieldset">
    <div class="form-group">
        <%= f.label :tutor, :class => 'col-sm-2 control-label' %>
        <div class="controls">

            <%= f.input :employee, 
                        :url => autocomplete_employee_name_course_classes_path, 
                        :as => :autocomplete,
                        :autofocus => true,
                        :label=> false,
                        :input_html => { 
                          :class => 'form-control', 
                          :autocomplete => 'off',
                          :style => 'max-width: 600px;',
                          :id_element=>'#employee_id'
                        } 
            %>

            <%= f.hidden_field :employee_id, :id => "employee_id", :name => "employee_id" %>
            <%= f.hidden_field :id, :id => "id", :name => "id" %>

        </div>

        <br>

        <%= f.submit 'Adicionar Tutor', 
              :disabled => !current_user.auth_to_edit('course_class') || @course_class.closed,
              :class => 'col-sm-offset-2 btn btn-primary' %>
        <%= link_to "Cadastrar Novo", 
              employees_add_for_select_path, 
              :disabled => !current_user.auth_to_add('employee') || @course_class.closed,
              :class => 'btn btn-success', 
              :target => "blank" %> 
        
    </div>
  </fieldset>

  <!-- TUTORS -->
  <div role="tabpanel" class="tab-pane active" id="students">
      <%- model_class = Employee -%>
      <table class="table table-striped">
        <thead>
          <tr>
            <th><%= model_class.human_attribute_name(:nome) %></th>
            <th><%= model_class.human_attribute_name(:telefone) %></th>
            <th><%= model_class.human_attribute_name(:email) %></th>
            <th><%=t '.actions', :default => "Ações" %></th>
          </tr>
        </thead>
        <tbody>
          <% @course_class.employees.each do |employee| %>
            <tr id="employee_<%=employee.id%>">
              <td><%= employee.name %></td>
              <td><%= employee.phone_number %></td>
              <td><%= employee.email %></td>
              <td>

              <%= link_to "Remove", 
                    course_classes_remove_employee_path(:id => @course_class.id, :employee_id => employee.id),
                    :data => { :confirm => t('.confirm', :default => 'Tem certeza que deseja remover o tutor dessa turma?') },
                    :disabled => !current_user.auth_to_edit('registration') || @course_class.closed,
                    :remote => true,
                    :class=>'btn btn-xs btn btn-danger' %>

              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    
  </div>

<%= link_to "Voltar", course_classes_path, :class => 'btn btn-default' %>
 
<% end %>

app/views/course_classes/_form_add_students.erb
<%= simple_form_for @course_class, 
    :html => { :class => "form-horizontal course_class"},
    :url => url_for(course_classes_add_student_path),
    :method => 'get' do |f| %>


  <div class="page-header">
    <h3>Matrículas</h3>
  </div>

  <% if @course_class.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-body">
        <ul>
        <% @course_class.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <!--GROUP FIND EMPLOYEE -->
  <fieldset class="well the-fieldset">
    <div class="form-group">
        <%= f.label :aluno, :class => 'col-sm-2 control-label' %>
        <div class="controls">

            <%= f.input :student, 
                        :url => autocomplete_student_name_course_classes_path, 
                        :as => :autocomplete,
                        :autofocus => true,
                        :label=> false,
                        :input_html => { 
                          :class => 'form-control', 
                          :autocomplete => 'off',
                          :style => 'max-width: 600px;',
                          :id_element=>'#student_id'
                        } 
            %>

            <%= f.hidden_field :student_id, :id => "student_id", :name => "student_id" %>
            <%= f.hidden_field :id, :id => "id", :name => "id" %>

        </div>

        <br>

        <%= f.submit 'Matricular Aluno', 
              :disabled => !current_user.auth_to_add('registration') || @course_class.closed,
              :class => 'col-sm-offset-2 btn btn-primary' %>
        <%= link_to "Cadastrar Novo", 
              students_add_for_select_path, 
              :disabled => !current_user.auth_to_add('student') || @course_class.closed,
              :class => 'btn btn-success', :target => "blank" %>
        
    </div>
  </fieldset>

  <!-- STUDENTS -->
  <div role="tabpanel" class="tab-pane active" id="students">
      <%- model_class = Student -%>
      <table class="table table-striped">
        <thead>
          <tr>
            <th><%= model_class.human_attribute_name(:nome) %></th>
            <th><%= model_class.human_attribute_name(:telefone) %></th>
            <th><%= model_class.human_attribute_name(:email) %></th>
            <th><%= model_class.human_attribute_name(:status) %></th>
            <th><%=t '.actions', :default => "Ações" %></th>
          </tr>
        </thead>
        <tbody>
          <% @course_class.registrations.each do |registration| %>
            <tr id="registration_<%=registration.id%>">
              <td><%= registration.student.name %></td>
              <td><%= registration.student.phone_number %></td>
              <td><%= registration.student.email %></td>
              <td><%= (registration.registration_status.nil? ? "" : registration.registration_status.name) %></td>
              <td>

              <%= link_to "Editar Matricula",
                    course_classes_registration_path(:registration_id => registration.id), 
                    :disabled => !current_user.auth_to_edit('registration') || @course_class.closed,
                    :class=>'btn btn-xs btn btn-primary' %>
              
              <%= link_to "Remover", 
                    course_classes_remove_registration_path(:id => @course_class.id, :registration_id => registration.id),
                    :data => { :confirm => t('.confirm', :default => 'Tem certeza que deseja excluir a matrícula?') },
                    :remote => true,
                    :disabled => !current_user.auth_to_remove('registration') || @course_class.closed,
                    :class=>'btn btn-xs btn btn-danger' %>

              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    
  </div>

  <%= link_to "Voltar", course_classes_path, :class => 'btn btn-default' %>                      

 
<% end %>

app/views/course_classes/destroy.js.erb
$("#course_class_<%=@course_class.id%>").hide('slow');

app/views/course_classes/destroy_document.js.erb
$("#document_<%=params[:document_id]%>").hide('slow');

app/views/course_classes/destroy_employee.js.erb
$("#employee_<%=params[:employee_id]%>").hide('slow');

app/views/course_classes/destroy_registration.js.erb
$("#registration_<%=params[:registration_id]%>").hide('slow');

app/views/course_classes/edit.html.erb
<%- model_class = CourseClass -%>
<div class="page-header">
  <h3><%=t '.title', :default => "Editando Turma" %></h3>
</div>
<%= render :partial => 'form' %>

app/views/course_classes/index.html.erb
<%- model_class = CourseClass -%>
<div class="page-header">
  <h3><%=t '.title', :default => "Turmas" %></h3>
</div>

<!-- FORM SEARCH -->
<%= form_tag(course_classes_path, :method => "get", id: "search-form", :class => "form-inline") do %>

  <fieldset class="well the-fieldset">
    <legend class="the-legend">Pesquisa</legend>
    <div class="form-group">
      <%= label_tag :nome %>
      <div class="controls">
        <%= text_field_tag :search_course_class_name, session[:search_course_class_name], 
           placeholder: "nome", :class => 'form-control', :style=> 'max-width: 600px' %>
      </div>
    </div>
    <div class="form-group">
      <%= label_tag "Instituição" %>
      <div class="controls">
        <%= text_field_tag :search_course_class_institution_name, session[:search_course_class_institution_name],
            placeholder: "instituição", :class => 'form-control', :style=> 'max-width: 600px' %>
      </div>
    </div>
    <div class="form-group">
      <%= label_tag :curso %>
      <div class="controls">
        <%= text_field_tag :search_course_class_course_name, session[:search_course_class_course_name],
            placeholder: "curso", :class => 'form-control', :style=> 'max-width: 600px' %>
      </div>
    </div>

    <%= submit_tag "Pesquisar", :class => 'btn btn-success sm', :style => "margin-top: 22px;" %>
    <%= link_to "Limpar", course_classes_clear_search_path, 
      :class => 'btn btn-default sm', :style => "margin-top: 22px;" %>

  </fieldset>

<% end %>

<%= link_to t('.new', :default => "Novo"),
      new_course_class_path,
      :disabled => !current_user.auth_to_add('course_class'),
      :class => 'btn btn-primary' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name("Instituição") %></th>
      <th><%= model_class.human_attribute_name(:curso) %></th>
      <% if current_user.admin? %>
      <th><%= model_class.human_attribute_name(:fechar) %></th>
      <%end%>
      <th><%= model_class.human_attribute_name("Informações da Turma") %></th>
      <th><%=t '.actions', :default => "Ações" %></th>
    </tr>
  </thead>
  <tbody>
    <% @course_classes.each do |course_class| %>
      <tr id="course_class_<%=course_class.id%>" style="<%= (course_class.closed? ? 'color: #999;' : '')%>">
        <td><%= course_class.id %></td>
        <td><%= course_class.name %></td>
        <td><%= course_class.institution.acronym %></td>
        <td><%= course_class.course.acronym %></td>
        <% if current_user.admin? %>
        <td>
          <%= 
            if course_class.closed?
              link_to "Reabrir", 
                course_classes_reopen_course_class_path(:id => course_class.id), 
                :class => 'btn btn-default btn-xs',
                :data => { :confirm => t('.confirm', :default => 'Tem certeza que deseja reabrir a turma?') }
            else
              link_to "Fechar  ", 
                course_classes_close_course_class_path(:id => course_class.id), 
                :class => 'btn btn-default btn-xs',
                :data => { :confirm => t('.confirm', :default => 'Tem certeza que deseja fechar a turma?') }
            end
          %>
        </td>
        <%end%>
        <td>
        <%= link_to 'Matrículas', 
              course_classes_registrations_path(:id=>course_class.id), 
              :disabled => !current_user.auth_to_view('registration'),
              :class => 'btn btn-success btn-xs' %>
        <%= link_to 'Tutores', 
              course_classes_employees_path(:id=>course_class.id), 
              :disabled => !current_user.auth_to_view('employee'),
              :class => 'btn btn-primary btn-xs' %>
        <%= link_to 'Documentos', 
              course_classes_documents_path(:id=>course_class.id), 
              :disabled => !current_user.auth_to_view('document'),
              :class => 'btn btn-warning btn-xs' %>
          <%= link_to 'Lista de Presença',
                course_classes_generate_list_of_presence_path(:id => course_class.id), 
                :disabled => !current_user.auth_to_view('registration'),
                :class => 'btn btn-default btn-xs' %>
        </td>
        <td>
          <%= link_to t('.edit', :default => "Editar"),
                edit_course_class_path(course_class), 
                :disabled => !current_user.auth_to_edit('course_class') || course_class.closed,
                :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => "Remover"),
                course_class_path(course_class),
                :disabled => !current_user.auth_to_remove('course_class') || course_class.closed,
                :remote => true,
                :method => :delete,
                :data => { :confirm => t('.confirm', :default => 'Tem certeza que deseja excluir?') },
                :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
    <tr>
      <td colspan="7">
        Exibindo <%= @course_classes.length %> de <%= @total %> turmas(s)
      </td>
    <tr>    
  </tbody>
</table>

<%= paginate @course_classes %>

app/views/course_classes/new.html.erb
<%- model_class = CourseClass -%>
<div class="page-header">
  <h3><%=t '.title', :default => "Nova Turma" %></h3>
</div>
<%= render :partial => 'form' %>