config/routes.rb
Rails.application.routes.draw do
	
  	authenticate :user do
	  #invoke add student to classes
	  get  "course_classes/registrations" => "course_classes#registrations"	
	  get  "course_classes/add_student" => "course_classes#add_student"	
	  get  "course_classes/remove_registration" => "course_classes#remove_registration"  
	  get  "course_classes/registration" => "course_classes#registration"  
	  get  "course_classes/employees" => "course_classes#employees"	
	  get  "course_classes/add_employee" => "course_classes#add_employee"	
	  get  "course_classes/remove_employee" => "course_classes#remove_employee"  
	  get  "course_classes/documents" => "course_classes#documents"	
	  post "course_classes/add_document" => "course_classes#add_document"
	  get  "course_classes/remove_document" => "course_classes#remove_document"  
	  get  "course_classes/clear_search" => "course_classes#clear_search"  
	  get  "course_classes/generate_list_of_presence" => "course_classes#generate_list_of_presence"  
	  get  "course_classes/close_course_class" => "course_classes#close_course_class"  
	  get  "course_classes/reopen_course_class" => "course_classes#reopen_course_class"  
	  get  "documents/download_file" => "documents#download_file"
	  get  "students/add_for_select" => "students#add_for_select"
	  get  "students/clear_search" => "students#clear_search"
	  get  "employees/add_for_select" => "employees#add_for_select"
	  get  "employees/clear_search" => "employees#clear_search"
      get  "cities/clear_search" => "cities#clear_search"
      get  "institutions/clear_search" => "institutions#clear_search"
      get  "courses/clear_search" => "courses#clear_search"
 	  get  "employee_categories/clear_search" => "employee_categories#clear_search"     
 	  get  "registration_statuses/clear_search" => "registration_statuses#clear_search"   
 	  get  "document_categories/clear_search" => "document_categories#clear_search"  
 	  get  "parameters/clear_search" => "parameters#clear_search"  
 	  post "accounts/update_user_account" => "accounts#update_user_account"  
 	  get  "accounts/activate_user" => "accounts#activate_user"  
 	  get  "accounts/inactivate_user" => "accounts#inactivate_user"  
 	  get  "accounts/roles" => "accounts#roles"	
	  get  "accounts/add_role" => "accounts#add_role"	
	  get  "accounts/remove_role" => "accounts#remove_role"    
	  get  "accounts/clear_search" => "accounts#clear_search"
	  get  "use_cases/clear_search" => "use_cases#clear_search"  
 	  get  "roles/clear_search" => "roles#clear_search"
 	  get  "roles/authorizations" => "roles#authorizations"	
 	  get  "roles/update_authorization" => "roles#update_authorization"
 	  get  "roles/add_for_select" => "roles#add_for_select"
 	  get  "registrations/clear_search" => "registrations#clear_search"
 	  get  "events/clear_search" => "events#clear_search"
 	  get  "events/previous_month" => "events#previous_month"
 	  get  "events/next_month" => "events#next_month"
 	  get  "events/add_participant" => "events#add_participant"
 	  get  "events/remove_participant" => "events#remove_participant"
 	  get  "events/participants" => "events#participants"

	  resources :events do
	  	get :autocomplete_employee_name, :on => :collection
	  end
	  resources :event_participants
	  resources :accounts
	  resources :roles
	  resources :authorizations
	  resources :use_cases
	  resources :documents
	  resources :employee_categories
	  resources :document_categories
	  resources :parameters	  
	  resources :registration_statuses
	  resources :institutions
	  resources :courses
	  resources :cities

	  resources :registrations do
	  	get :autocomplete_course_class_name, :on => :collection
	  end
	  
  	  resources :employees do
  	  	get :autocomplete_city_name, :on => :collection
  	  end

	  resources :students do
	  	get :autocomplete_city_name, :on => :collection
	  end

	  resources :course_classes do
	  	get :autocomplete_student_name, :on => :collection
	  	get :autocomplete_employee_name, :on => :collection
	  end

	end

	devise_for :users 
	devise_scope :user do
	  authenticated :user do
	    root 'visitors#index', as: :authenticated_root
	  end

	  unauthenticated do
	    root 'devise/sessions#new', as: :unauthenticated_root
	  end
	end

	root :to => "visitors#index"
end

app/controllers/registration_statuses_controller.rb
class RegistrationStatusesController < ApplicationController
  before_action :set_registration_status, only: [:show, :edit, :update, :destroy]
  respond_to :html, :js
  
  include ModelSearchHelper

  def index
    @registration_statuses = self.search(params, RegistrationStatus)
    respond_with(@registration_statuses)
  end  
  
  def show
    respond_with(@registration_status)
  end

  def new
    @registration_status = RegistrationStatus.new
    respond_with(@registration_status)
  end

  def create
    @registration_status = RegistrationStatus.new(registration_status_params)
    if @registration_status.save
      redirect_to action: "index"  
    else
      respond_with(@registration_status)  
    end
  end

  def update
    if @registration_status.update(registration_status_params)
      redirect_to action: "index"  
    else
      respond_with(@registration_status)  
    end
  end

  def destroy
    @registration_status.destroy
  end

  def clear_search
    session.delete :search_registration_status_name
    redirect_to action: "index"
  end

  private
    def set_registration_status
      @registration_status = RegistrationStatus.find(params[:id])
    end

    def registration_status_params
      params.require(:registration_status).permit(:name, :show_list_of_presence)
    end
end

app/helpers/registration_statuses_helper.rb
module RegistrationStatusesHelper
end

app/views/registration_statuses/_form.html.erb
<%= simple_form_for @registration_status, :html => { :class => 'form-horizontal' } do |f| %>
  <% if @registration_status.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-body">
        <ul>
        <% @registration_status.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, :class => 'col-sm-2 control-label' %>
    <div class="controls">
      <%= f.text_field :name, :autofocus => true, :class => 'form-control', :style=> 'max-width: 600px'  %>
    </div>
    <%= error_span(@registration_status[:name]) %>
  </div>

  <div class="form-group">
    <%= f.label "Gera Lista de Presença", :class => 'col-sm-2 control-label' %>
    <div class="controls">
      <%= f.select(:show_list_of_presence, [['SIM', true], ['NÃO', false]], 
          {:value => :show_list_of_presence}, 
          {:class =>'form-control', :style=> 'max-width: 100px'}) %>
    </div>
    <%= error_span(@registration_status[:show_list_of_presence]) %>
  </div>

  <%= error_span(@registration_status[:name]) %>

  <%= f.submit "Salvar Status", :class => 'col-sm-offset-2 btn btn-primary' %>
  <%= link_to "Cancelar", registration_statuses_path, :class => 'btn btn-default' %>

<% end %>

app/views/registration_statuses/destroy.js.erb
$("#registration_status_<%=@registration_status.id%>").hide('slow');

app/views/registration_statuses/edit.html.erb
<%- model_class = RegistrationStatus -%>
<div class="page-header">
  <h3><%=t '.title', :default => "Editando Status de Matrícula" %></h3>
</div>
<%= render :partial => 'form' %>

app/views/registration_statuses/index.html.erb
<%- model_class = RegistrationStatus -%>
<div class="page-header">
  <h3><%=t '.title', :default => "Status Matricula" %></h3>
</div>

<!-- FORM SEARCH -->
<%= form_tag(registration_statuses_path, :method => "get", id: "search-form", :class => "form-inline registration_status") do %>

  <fieldset class="well the-fieldset">
    <legend class="the-legend">Pesquisa</legend>
    <div class="form-group">
      <%= label_tag :nome %>
      <div class="controls">
        <%= text_field_tag :search_registration_status_name, session[:search_registration_status_name], :class => 'form-control', :style=> 'max-width: 600px' %>
      </div>
    </div>

    <%= submit_tag "Pesquisar", :class => 'btn btn-success sm', :style => "margin-top: 22px;" %>
    <%= link_to "Limpar", registration_statuses_clear_search_path, 
          :class => 'btn btn-default sm', :style => "margin-top: 22px;" %>

  </fieldset>

<% end %>

<%= link_to t('.new', :default => "Novo"),
      new_registration_status_path,
      :disabled => !current_user.auth_to_add('registration_status'),
      :class => 'btn btn-primary' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= "Gera Lista Presença" %></th>
      <th><%=t '.actions', :default => "Ações" %></th>
    </tr>
  </thead>
  <tbody>
    <% @registration_statuses.each do |registration_status| %>
      <tr id="registration_status_<%=registration_status.id%>">
        <td><%= registration_status.id %></td>
        <td><%= registration_status.name %></td>
        <td><%= (registration_status.show_list_of_presence? ? "SIM" : "NÃO") %></td>
        <td>
          <%= link_to t('.edit', :default => "Editar"),
                edit_registration_status_path(registration_status),
                :disabled => !current_user.auth_to_edit('registration_status'), 
                :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => "Remover"),
                registration_status_path(registration_status),
                :disabled => !current_user.auth_to_remove('registration_status'),
                :remote => true,
                :method => :delete,
                :data => { :confirm => t('.confirm', :default => 'Tem certeza que deseja excluir?') },
                :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
    <tr>
      <td colspan="7">
        Exibindo <%= @registration_statuses.length %> de <%= @total %> status
      </td>
    <tr>
  </tbody>
</table>
<%= paginate @registration_statuses %>

app/views/registration_statuses/new.html.erb
<%- model_class = RegistrationStatus -%>
<div class="page-header">
  <h3><%=t '.title', :default => "Novo Status de Matrícula" %></h3>
</div>
<%= render :partial => 'form' %>

app/views/registration_statuses/show.html.erb
<%- model_class = RegistrationStatus -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @registration_status.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              registration_statuses_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_registration_status_path(@registration_status), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              registration_status_path(@registration_status),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>