config/routes.rb
Rails.application.routes.draw do
	
  	authenticate :user do
	  #invoke add student to classes
	  get  "course_classes/registrations" => "course_classes#registrations"	
	  get  "course_classes/add_student" => "course_classes#add_student"	
	  get  "course_classes/remove_registration" => "course_classes#remove_registration"  
	  get  "course_classes/registration" => "course_classes#registration"  
	  get  "course_classes/employees" => "course_classes#employees"	
	  get  "course_classes/add_employee" => "course_classes#add_employee"	
	  get  "course_classes/remove_employee" => "course_classes#remove_employee"  
	  get  "course_classes/documents" => "course_classes#documents"	
	  post "course_classes/add_document" => "course_classes#add_document"
	  get  "course_classes/remove_document" => "course_classes#remove_document"  
	  get  "course_classes/clear_search" => "course_classes#clear_search"  
	  get  "course_classes/generate_list_of_presence" => "course_classes#generate_list_of_presence"  
	  get  "course_classes/close_course_class" => "course_classes#close_course_class"  
	  get  "course_classes/reopen_course_class" => "course_classes#reopen_course_class"  
	  get  "documents/download_file" => "documents#download_file"
	  get  "students/add_for_select" => "students#add_for_select"
	  get  "students/clear_search" => "students#clear_search"
	  get  "employees/add_for_select" => "employees#add_for_select"
	  get  "employees/clear_search" => "employees#clear_search"
      get  "cities/clear_search" => "cities#clear_search"
      get  "institutions/clear_search" => "institutions#clear_search"
      get  "courses/clear_search" => "courses#clear_search"
 	  get  "employee_categories/clear_search" => "employee_categories#clear_search"     
 	  get  "registration_statuses/clear_search" => "registration_statuses#clear_search"   
 	  get  "document_categories/clear_search" => "document_categories#clear_search"  
 	  get  "parameters/clear_search" => "parameters#clear_search"  
 	  post "accounts/update_user_account" => "accounts#update_user_account"  
 	  get  "accounts/activate_user" => "accounts#activate_user"  
 	  get  "accounts/inactivate_user" => "accounts#inactivate_user"  
 	  get  "accounts/roles" => "accounts#roles"	
	  get  "accounts/add_role" => "accounts#add_role"	
	  get  "accounts/remove_role" => "accounts#remove_role"    
	  get  "accounts/clear_search" => "accounts#clear_search"
	  get  "use_cases/clear_search" => "use_cases#clear_search"  
 	  get  "roles/clear_search" => "roles#clear_search"
 	  get  "roles/authorizations" => "roles#authorizations"	
 	  get  "roles/update_authorization" => "roles#update_authorization"
 	  get  "roles/add_for_select" => "roles#add_for_select"
 	  get  "registrations/clear_search" => "registrations#clear_search"
 	  get  "events/clear_search" => "events#clear_search"
 	  get  "events/previous_month" => "events#previous_month"
 	  get  "events/next_month" => "events#next_month"
 	  get  "events/add_participant" => "events#add_participant"
 	  get  "events/remove_participant" => "events#remove_participant"
 	  get  "events/participants" => "events#participants"

	  resources :events do
	  	get :autocomplete_employee_name, :on => :collection
	  end
	  resources :event_participants
	  resources :accounts
	  resources :roles
	  resources :authorizations
	  resources :use_cases
	  resources :documents
	  resources :employee_categories
	  resources :document_categories
	  resources :parameters	  
	  resources :registration_statuses
	  resources :institutions
	  resources :courses
	  resources :cities

	  resources :registrations do
	  	get :autocomplete_course_class_name, :on => :collection
	  end
	  
  	  resources :employees do
  	  	get :autocomplete_city_name, :on => :collection
  	  end

	  resources :students do
	  	get :autocomplete_city_name, :on => :collection
	  end

	  resources :course_classes do
	  	get :autocomplete_student_name, :on => :collection
	  	get :autocomplete_employee_name, :on => :collection
	  end

	end

	devise_for :users 
	devise_scope :user do
	  authenticated :user do
	    root 'visitors#index', as: :authenticated_root
	  end

	  unauthenticated do
	    root 'devise/sessions#new', as: :unauthenticated_root
	  end
	end

	root :to => "visitors#index"
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  respond_to :html, :js
  
  include ModelSearchHelper

  def index
    @courses = self.search(params, Course)
    respond_with(@courses)
  end

  def show
    respond_with(@course)
  end

  def new
    @course = Course.new
    respond_with(@course)
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to action: "index"
    else
      respond_with(@course)  
    end
  end

  def update
    if @course.update(course_params)
      redirect_to action: "index"
    else
      respond_with(@course)  
    end
  end

  def destroy
    @course.destroy
  end

  def clear_search
    session.delete :search_course_name
    redirect_to action: "index"
  end

  private
    def set_course
      @course = Course.find(params[:id])
    end

    def course_params
      params.require(:course).permit(:name, :acronym)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= simple_form_for @course, :html => { :class => 'form-horizontal course' } do |f| %>
    <% if @course.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-body">
        <ul>
        <% @course.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, :class => 'col-sm-2 control-label' %>
    <div class="controls">
      <%= f.text_field :name, :autofocus => true, :class => 'form-control', :style=> 'max-width: 600px' %>
    </div>
    <%= error_span(@course[:name]) %>
  </div>

   <div class="form-group">
    <%= f.label :sigla, :class => 'col-sm-2 control-label' %>
    <div class="controls">
      <%= f.text_field :acronym, :class => 'form-control', :style=> 'max-width: 100px' %>
    </div>
    <%= error_span(@course[:acronym]) %>
  </div>

  <br>

  <%= f.submit "Salvar Curso", :class => 'col-sm-offset-2 btn btn-primary' %>
  <%= link_to "Cancelar", courses_path, :class => 'btn btn-default' %>

<% end %>

app/views/courses/destroy.js.erb
$("#course_<%=@course.id%>").hide('slow');

app/views/courses/edit.html.erb
<%- model_class = Course -%>
<div class="page-header">
  <h3><%=t '.title', :default => "Editando Curso" %></h3>
</div>
<%= render :partial => 'form' %>

app/views/courses/index.html.erb
<%- model_class = Course -%>
<div class="page-header">
  <h3><%=t '.title', :default => "Cursos" %></h3>
</div>

<!-- FORM SEARCH -->
<%= form_tag(courses_path, :method => "get", id: "search-form", :class => "form-inline city") do %>

  <fieldset class="well the-fieldset">
    <legend class="the-legend">Pesquisa</legend>
    <div class="form-group">
      <%= label_tag :nome %>
      <div class="controls">
        <%= text_field_tag :search_course_name, session[:search_course_name], :class => 'form-control', :style=> 'max-width: 600px' %>
      </div>
    </div>

    <%= submit_tag "Pesquisar", :class => 'btn btn-success sm', :style => "margin-top: 22px;" %>
    <%= link_to "Limpar", courses_clear_search_path, 
          :class => 'btn btn-default sm', :style => "margin-top: 22px;" %>

  </fieldset>

<% end %>

<%= link_to t('.new', :default => "Novo"),
      new_course_path,
      :disabled => !current_user.auth_to_add('course'),
      :class => 'btn btn-primary' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:sigla) %></th>
      <th><%=t '.actions', :default => "Ações" %></th>
    </tr>
  </thead>
  <tbody>
    <% @courses.each do |course| %>
      <tr id="course_<%=course.id%>">
        <td><%= link_to course.id, course_path(course) %></td>
        <td style="width:50%"><%= course.name %></td>
        <td><%= course.acronym %></td>
        <td>
          <%= link_to t('.edit', :default => "Editar"),
              edit_course_path(course),
              :disabled => !current_user.auth_to_edit('course'), 
              :class => 'btn btn-default btn-xs' %>

          <%= link_to t('.destroy', :default => "Remover"),
                course_path(course),
                :disabled => !current_user.auth_to_remove('course'),
                :remote => true,
                :method => :delete,
                :data => { :confirm => t('.confirm', :default => 'Tem certeza que deseja excluir?') },
                :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
    <tr>
      <td colspan="7">
        Exibindo <%= @courses.length %> de <%= @total %> curso(s)
      </td>
    <tr>
  </tbody>
</table>
<%= paginate @courses %>

app/views/courses/new.html.erb
<%- model_class = Course -%>
<div class="page-header">
  <h3><%=t '.title', :default => "Novo Curso" %></h3>
</div>
<%= render :partial => 'form' %>

app/views/courses/show.html.erb
<%- model_class = Course -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @course.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              courses_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_course_path(@course), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              course_path(@course),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>