config/routes.rb
Rails.application.routes.draw do
	
  	authenticate :user do
	  #invoke add student to classes
	  get  "course_classes/registrations" => "course_classes#registrations"	
	  get  "course_classes/add_student" => "course_classes#add_student"	
	  get  "course_classes/remove_registration" => "course_classes#remove_registration"  
	  get  "course_classes/registration" => "course_classes#registration"  
	  get  "course_classes/employees" => "course_classes#employees"	
	  get  "course_classes/add_employee" => "course_classes#add_employee"	
	  get  "course_classes/remove_employee" => "course_classes#remove_employee"  
	  get  "course_classes/documents" => "course_classes#documents"	
	  post "course_classes/add_document" => "course_classes#add_document"
	  get  "course_classes/remove_document" => "course_classes#remove_document"  
	  get  "course_classes/clear_search" => "course_classes#clear_search"  
	  get  "course_classes/generate_list_of_presence" => "course_classes#generate_list_of_presence"  
	  get  "course_classes/close_course_class" => "course_classes#close_course_class"  
	  get  "course_classes/reopen_course_class" => "course_classes#reopen_course_class"  
	  get  "documents/download_file" => "documents#download_file"
	  get  "students/add_for_select" => "students#add_for_select"
	  get  "students/clear_search" => "students#clear_search"
	  get  "employees/add_for_select" => "employees#add_for_select"
	  get  "employees/clear_search" => "employees#clear_search"
      get  "cities/clear_search" => "cities#clear_search"
      get  "institutions/clear_search" => "institutions#clear_search"
      get  "courses/clear_search" => "courses#clear_search"
 	  get  "employee_categories/clear_search" => "employee_categories#clear_search"     
 	  get  "registration_statuses/clear_search" => "registration_statuses#clear_search"   
 	  get  "document_categories/clear_search" => "document_categories#clear_search"  
 	  get  "parameters/clear_search" => "parameters#clear_search"  
 	  post "accounts/update_user_account" => "accounts#update_user_account"  
 	  get  "accounts/activate_user" => "accounts#activate_user"  
 	  get  "accounts/inactivate_user" => "accounts#inactivate_user"  
 	  get  "accounts/roles" => "accounts#roles"	
	  get  "accounts/add_role" => "accounts#add_role"	
	  get  "accounts/remove_role" => "accounts#remove_role"    
	  get  "accounts/clear_search" => "accounts#clear_search"
	  get  "use_cases/clear_search" => "use_cases#clear_search"  
 	  get  "roles/clear_search" => "roles#clear_search"
 	  get  "roles/authorizations" => "roles#authorizations"	
 	  get  "roles/update_authorization" => "roles#update_authorization"
 	  get  "roles/add_for_select" => "roles#add_for_select"
 	  get  "registrations/clear_search" => "registrations#clear_search"
 	  get  "events/clear_search" => "events#clear_search"
 	  get  "events/previous_month" => "events#previous_month"
 	  get  "events/next_month" => "events#next_month"
 	  get  "events/add_participant" => "events#add_participant"
 	  get  "events/remove_participant" => "events#remove_participant"
 	  get  "events/participants" => "events#participants"

	  resources :events do
	  	get :autocomplete_employee_name, :on => :collection
	  end
	  resources :event_participants
	  resources :accounts
	  resources :roles
	  resources :authorizations
	  resources :use_cases
	  resources :documents
	  resources :employee_categories
	  resources :document_categories
	  resources :parameters	  
	  resources :registration_statuses
	  resources :institutions
	  resources :courses
	  resources :cities

	  resources :registrations do
	  	get :autocomplete_course_class_name, :on => :collection
	  end
	  
  	  resources :employees do
  	  	get :autocomplete_city_name, :on => :collection
  	  end

	  resources :students do
	  	get :autocomplete_city_name, :on => :collection
	  end

	  resources :course_classes do
	  	get :autocomplete_student_name, :on => :collection
	  	get :autocomplete_employee_name, :on => :collection
	  end

	end

	devise_for :users 
	devise_scope :user do
	  authenticated :user do
	    root 'visitors#index', as: :authenticated_root
	  end

	  unauthenticated do
	    root 'devise/sessions#new', as: :unauthenticated_root
	  end
	end

	root :to => "visitors#index"
end

app/controllers/accounts_controller.rb
    class AccountsController < ApplicationController

  respond_to :html, :js

  include ModelSearchHelper

  def index
    #@users = Array.new
    #@users << User.where("super = ? ", true) if current_user.super?
    @users = self.search(params, User)
  end

  def show
    respond_with(@user)
  end

  def edit
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.admin = false
    @user.active = true
    if @user.save
      redirect_to :action => 'index'
    else
      render :action => 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update_user_account

    @user = User.find(params[:id])

    if @user.id != current_user.id
      @user.active = params[:active]
      @user.admin  = params[:admin]
    end

    params[:user].delete(:password) if params[:user][:password].blank?
    params[:user].delete(:password_confirmation) if params[:user][:password].blank? and params[:user][:password_confirmation].blank?
    if @user.update_attributes(user_params)
      redirect_to :action => 'index'
    else
      render :action => 'edit'
    end

  end

  def destroy
    #@user = User.find(params[:id])
    @user.destroy
  end 

  def activate_user
    @user = User.find(params[:id])
    if @user.update(:active => true)
      flash[:notice] = "Usuário ativado com sucesso!"
    else
      flash[:error] = "Erro ao ativar usuário!"
    end
    redirect_to action: "index"
  end 

  def inactivate_user
    @user = User.find(params[:id])
    if @user.update(:active => false)
      flash[:notice] = "Usuário inativado com sucesso!"
    else
      flash[:error] = "Erro ao inativar usuário!"
    end
    redirect_to action: "index"
  end   

  def roles
    @user = User.find(params[:id])
    render '_form_roles'
  end

  def add_role

    @user = User.find(params[:id])
    #impede que uma mesma role seja adicinada mais de uma vez para o mesmo usuário
    if role_already_added(params[:user][:role_id], params[:id])
      render '_form_roles'
      return
    end

    #limpa os erros que podem existir da requisição anterior
    @user.errors.clear

    begin
      @role = Role.find(params[:user][:role_id])
    rescue
      @user.errors.add(:info, "Papel não encontrado. Por favor selecione um papel válido. ")
    end
    
    #if occurred any erros, back to page
    if @user.errors.any?
      render '_form_roles'
      return
    end

    @user.roles << @role
    #@role.users << @user
    @user.save

    redirect_to :back
 
  end

  def role_already_added(role_id, user_id)
    role = User.joins(:roles).where('roles.id = ? and users.id = ?', role_id, user_id)
    !role.nil? && role.length > 0
  end

  def remove_role
    @user = User.find(params[:id])
    @user.roles.delete(params[:role_id])
    render "destroy_role"
  end

  def clear_search
    session.delete :search_user_name
    session.delete :search_user_status
    redirect_to action: "index"
  end

  private
	  def set_user
	    @user = User.find(params[:id])
	  end
	 
	  def user_params
	    params.require(:user).permit(:id, :name, :email, :password, :password_confirmation, :admin, :active)
	  end

end

app/views/accounts/_form_edit.html.erb
<%= form_for @user, url: accounts_update_user_account_path(@user), :html => {method: :post, :class => "form-horizontal user" } do |f| %>

    <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <%= f.hidden_field :id, :id => "id", :name => "id" %>

  <div class="form-group">
      <%= f.label :nome, class: 'col-sm-2 control-label'  %>
      <div class="col-sm-6">
          <%= f.text_field :name, class: 'form-control'  %>
      </div>
  </div>

  <div class="form-group">
      <%= f.label :email, class: 'col-sm-2 control-label'  %>
      <div class="col-sm-6">
          <%= f.email_field :email, class: 'form-control'  %>
      </div>
  </div>

  <div class="form-group">
      <%= f.label :senha, class: 'col-sm-2 control-label'  %> <i>(deixe em branco se não deseja alterar)</i>
      <div class="col-sm-6">
          <%= f.password_field :password, autocomplete: "off", class: 'form-control'  %>
      </div>
  </div>

  <div class="form-group">
      <%= f.label "Confirmação Senha", class: 'col-sm-2 control-label' %>
      <div class="col-sm-6">
          <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control'  %>
      </div>
  </div>

  <% if current_user.id != @user.id %>
    <div class="form-group">
      <%= f.label "Administrador", :class => 'col-sm-2 control-label' %>
      <div class="col-sm-6">
        <%= select_tag :admin, 
            options_for_select([["SIM", true], ["NÃO", false]], @user.admin), 
            :class => 'form-control', :style=> 'width: 120px' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "Ativo", :class => 'col-sm-2 control-label' %>
      <div class="col-sm-6">
        <%= select_tag :active, 
            options_for_select([["SIM", true], ["NÃO", false]], @user.active), 
            :class => 'form-control', :style=> 'width: 120px' %>
      </div>
    </div>
  <% end %>

  <%= f.submit "Salvar Usuário", :class => 'col-sm-offset-2 btn btn-primary' %>
  <%= link_to "Cancelar", accounts_path, :class => 'btn btn-default' %>

<% end %>

app/views/accounts/_form_new.html.erb
<%= form_for @user, url: accounts_path, :html => { method: :post, :class => "form-horizontal user" } do |f| %>

    <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
      <%= f.label :nome, class: 'col-sm-2 control-label'  %>
      <div class="col-sm-6">
          <%= f.text_field :name, class: 'form-control'  %>
      </div>
  </div>

  <div class="form-group">
      <%= f.label :email, class: 'col-sm-2 control-label'  %>
      <div class="col-sm-6">
          <%= f.email_field :email, class: 'form-control'  %>
      </div>
  </div>

  <div class="form-group">
      <%= f.label :senha, class: 'col-sm-2 control-label'  %>
      <div class="col-sm-6">
          <%= f.password_field :password, autocomplete: "off", class: 'form-control'  %>
      </div>
  </div>


  <div class="form-group">
      <%= f.label "Confirmação Senha", class: 'col-sm-2 control-label' %>
      <div class="col-sm-6">
          <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control'  %>
      </div>
  </div>

  <%= f.submit "Salvar Usuário", :class => 'col-sm-offset-2 btn btn-primary' %>
  <%= link_to "Cancelar", accounts_path, :class => 'btn btn-default' %>

<% end %>

app/views/accounts/_form_roles.html.erb
<%= simple_form_for @user, 
    :html => { :class => "form-horizontal user"},
    :url => url_for(accounts_add_role_path),
    :method => 'get' do |f| %>

  <div class="page-header">
    <h3>Papéis do usuário <%= @user.name %></h3>
  </div>

  <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <!--GROUP FIND ROLE -->
  <fieldset class="well the-fieldset">
    <div class="form-inline">
        <%= f.label :papel, :class => 'col-sm-2 control-label' %>

        <%= f.select(:role_id, Role.all.map{ |r| [r.name, r.id]}, 
            {:value => :role_id}, 
            {:class =>'form-control', :style => "width:300px"})%>

        <%= f.hidden_field :id, :id => "id", :name => "id" %>

        <%= f.submit 'Adicionar Papel ao Usuário', 
              :disabled => !current_user.admin?,
              :class => 'col-sm-offset-2 btn btn-primary',
              :style => 'margin-left: 0px;' %>
        
    </div>
  </fieldset>

  <!-- ROLES -->
  <div role="tabpanel" class="tab-pane active" id="roles">
      <%- model_class = Role -%>
      <table class="table table-striped">
        <thead>
          <tr>
            <th><%= model_class.human_attribute_name(:id) %></th>
            <th><%= model_class.human_attribute_name(:papel) %></th>
            <th><%=t '.actions', :default => "Ações" %></th>
          </tr>
        </thead>
        <tbody>
          <% @user.roles.each do |role| %>
            <tr id="role_<%=role.id%>">
              <td><%= role.id%></td>
              <td><%= role.name %></td>
              <td>
                <%= 
                  link_to "Permissões", 
                    roles_authorizations_path(:id => role.id), 
                    :disabled => !current_user.admin?,
                    :class => 'btn btn-default btn-xs' %>        

                <%= 
                  link_to t('.destroy', :default => "Remover Papel"),
                    accounts_remove_role_path(:id => @user.id, :role_id => role.id),
                    :data => { :confirm => t('.confirm', :default => 'Tem certeza que deseja remover o papel do usuário?') },
                    :disabled => !current_user.admin?,
                    :remote => true,
                    :class=>'btn btn-xs btn btn-danger'
                %>

              </td>
            
            </tr>
          <% end %>
        </tbody>
      </table>

      <%= error_span(@user[:begin]) %>
    
  </div>

  <%= link_to "Voltar", accounts_path, :class => 'btn btn-default' %>                      

 
<% end %>

app/views/accounts/destroy.js.erb
$("#user_<%=@user.id%>").hide('slow');

app/views/accounts/destroy_role.js.erb
$("#role_<%=params[:role_id]%>").hide('slow');

app/views/accounts/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h3><%=t '.title', :default => "Editando Usuário" %></h3>
</div>
<%= render :partial => 'form_edit' %>

app/views/accounts/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h3><%=t '.title', :default => "Usuários" %></h3>
</div>

<!-- FORM SEARCH -->
<%= form_tag(accounts_path, :method => "get", id: "search-form", :class => "form-inline user") do %>

  <fieldset class="well the-fieldset">
    <legend class="the-legend">Pesquisa</legend>
    <div class="form-group">
      <%= label_tag :nome %>
      <div class="controls">
        <%= text_field_tag :search_user_name, session[:search_user_name], :class => 'form-control', :style=> 'max-width: 600px' %>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag :status %>
      <div class="controls">
        <%= select_tag :search_user_status, 
            options_for_select([["TODOS", "all"], ["ATIVO","active"], ["INATIVO", "inactive"]], session[:search_user_status]),
            :class => 'form-control', :style=> 'width: 120px' %>
      </div>
    </div>

    <%= submit_tag "Pesquisar", :class => 'btn btn-success sm', :style => "margin-top: 22px;" %>
    <%= link_to "Limpar", accounts_clear_search_path, 
          :class => 'btn btn-default sm', :style => "margin-top: 22px;" %>

  </fieldset>

<% end %>

<%= link_to t('.new', :default => "Novo"),
      new_account_path,
      :disabled => !current_user.admin?,
      :class => 'btn btn-primary' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name("Último Login") %></th>
      <th><%= model_class.human_attribute_name("Papéis") %></th>
      <th><%=t '.actions', :default => "Ativar/Inativar" %></th>
      <th><%=t '.actions', :default => "Ações" %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr id="user_<%=user.id%>">
        <td><%= user.id%></td>
        <td><%= user.name%></td>
        <td><%= user.email%></td>
        <td><%= user.last_sign_in_at%></td>
        <td>
          <%= 
            link_to "Papéis", 
              accounts_roles_path(:id => user.id), 
              :disabled => !current_user.admin?,
              :class => 'btn btn-success btn-xs' %>        
        </td>
        <td>
          <%= 
            if user.active?
              link_to "Inativar", 
                accounts_inactivate_user_path(:id => user.id), 
                :class => 'btn btn-default btn-xs',
                :disabled => !current_user.admin?,
                :data => { :confirm => t('.confirm', :default => 'Tem certeza que deseja inativar o usuário?') }
            else
              link_to "Ativar  ", accounts_activate_user_path(:id => user.id), :class => 'btn btn-default btn-xs',
                :data => { :confirm => t('.confirm', :default => 'Tem certeza que deseja ativar o usuário?') },
                :disabled => !current_user.admin?
            end
          %>
        </td>
        <td>
          <%= link_to t('.edit', :default => "Editar"),
                edit_account_path(user), 
                :disabled => !current_user.admin?,
                :class => 'btn btn-default btn-xs' %>

            <%= link_to t('.destroy', :default => "Remover"),
                account_path(user),
                :disabled => !current_user.admin?,
                :remote => true,
                :method => :delete,
                :data => { :confirm => t('.confirm', :default => 'Tem certeza que deseja excluir?') },
                :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
    <tr>
      <td colspan="7">
        Exibindo <%= @users.length %> de <%= @total %> usuário(s)
      </td>
    <tr>
  </tbody>
</table>

app/views/accounts/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h3><%=t '.title', :default => "Novo Usuário" %> </h3>
</div>
<%= render :partial => 'form_new' %>